// lib/products.js
export const products = [
  {
    slug: "keys",
    page_name: "Keys",
    canonical: "https://www.bestechparts.ae/products/keys",
    items: [
      { url: "/keys/door-open-key" },
      { url: "/keys/s-key-type-102" },
      { url: "/keys/key-type-ta6461" },
      { url: "/keys/k-key" },
      { url: "/keys/h-key" },
    ],
  },
  {
    slug: "tool-kits",
    page_name: "Tool Kits",
    canonical: "https://www.bestechparts.ae/products/tool-kits",
    items: [
      { url: "/tool-kits/k-tool-kit" },
      { url: "/tool-kits/o-tool-kit" },
      { url: "/tool-kits/tool-kit-keypad" },
    ],
  },
  {
    slug: "pcb-boards",
    page_name: "PCB Boards",
    canonical: "https://www.bestechparts.ae/products/pcb-boards",
    items: [
      { url: "/pcb-boards/car-top-board-mctc-ctb-a" },
      { url: "/pcb-boards/command-board-mctc-ccb-a" },
      { url: "/pcb-boards/car-top-board-step" },
      { url: "/pcb-boards/cop-command-board-step" },
      { url: "/pcb-boards/group-control-board-mctc-gcb-b1-a1" },
      { url: "/pcb-boards/ucmp-mctc-scb-a1" },
    ],
  },
  {
    slug: "displays",
    page_name: "Displays",
    canonical: "https://www.bestechparts.ae/products/displays",
    items: [
      { url: "/displays/cop-display-green-mctc-hcb-r1" },
      { url: "/displays/cop-display-black-mctc-hcb-r1" },
      { url: "/displays/lop-display-led" },
      { url: "/displays/dot-matrix-display-vertical" },
      { url: "/displays/dot-matrix-display-horizontal" },
      { url: "/displays/lcd-display-vertical" },
      { url: "/displays/lcd-display-horizontal" },
      { url: "/displays/display-led-4-3" },
      { url: "/displays/lcd-display-sftc-hcb-sl-blue" },
    ],
  },
  {
    slug: "signalization",
    page_name: "Signalization",
    canonical: "https://www.bestechparts.ae/products/signalization",
    items: [
      { url: "/signalization/lop-up-and-down" },
      { url: "/signalization/lop-up-lock" },
      { url: "/signalization/lop-down" },
      { url: "/signalization/duplex-lop-up-and-down" },
      { url: "/signalization/duplex-lop-up-lock" },
      { url: "/signalization/duplex-lop-down" },
    ],
  },
  {
    slug: "door-drives",
    page_name: "Door Drives",
    canonical: "https://www.bestechparts.ae/products/door-drives",
    items: [
      { url: "/door-drives/door-drive-bs-dd0001" },
      { url: "/door-drives/door-drive-bs-dd0002" },
    ],
  },
  {
    slug: "ard",
    page_name: "ARD",
    canonical: "https://www.bestechparts.ae/products/ard",
    items: [
      { url: "/ard/ard-7kw-ard-4007-3p" },
      { url: "/ard/ard-11kw-ard-4011-3p" },
      { url: "/ard/ard-4015-3p" },
    ],
  },
  {
    slug: "inverters",
    page_name: "Inverters",
    canonical: "https://www.bestechparts.ae/products/inverters",
    items: [
      { url: "/inverters/inverter-7-5kw-nice-l-c-4007" },
      { url: "/inverters/inverter-11kw-nice-l-c-4011" },
      { url: "/inverters/inverter-15kw-nice-l-c-4015" },
      { url: "/inverters/inverter-18kw-nice-l-c-4018" },
      { url: "/inverters/inverter-22kw-nice-l-c-4022" },
      { url: "/inverters/inverter-11kw-as380" },
    ],
  },
  {
    slug: "encoders",
    page_name: "Encoders",
    canonical: "https://www.bestechparts.ae/products/encoders",
    items: [
      { url: "/encoders/encoder-cable-5m" },
      { url: "/encoders/encoder-cable-10m" },
      { url: "/encoders/encoder-cable-15m" },
      { url: "/encoders/encoder-roller-37mm" },
      { url: "/encoders/encoder-roller-75mm" },
      { url: "/encoders/encoder-1387" },
      { url: "/encoders/encoder-1024-30mm" },
      { url: "/encoders/encoder-1024-35mm" },
      { url: "/encoders/encoder-1024-40mm" },
      { url: "/encoders/encoder-1024-45mm" },
      { url: "/encoders/encoder-pg-card-mctc-pg-e" },
      { url: "/encoders/encoder-pg-card-mctc-pg-a2" },
      { url: "/encoders/ecn-1313-encoder-with-7m-cable" },
      { url: "/encoders/encoder-ern-1387" },
    ],
  },
  {
    slug: "door-sliders",
    page_name: "Door Sliders",
    canonical: "https://www.bestechparts.ae/products/door-sliders",
    items: [
      { url: "/door-sliders/k-door-slider" },
      { url: "/door-sliders/o-door-slider" },
      { url: "/door-sliders/o-nylon-rubber-door-slider" },
      { url: "/door-sliders/door-slider-k200-s200" },
      { url: "/door-sliders/s-door-slider" },
      { url: "/door-sliders/lg-door-slider" },
      { url: "/door-sliders/to-door-slider" },
      { url: "/door-sliders/hi-door-slider" },
      { url: "/door-sliders/e-door-slider" },
      { url: "/door-sliders/hy-door-slider" },
      { url: "/door-sliders/c-door-slider" },
      { url: "/door-sliders/i-door-slider" },
      { url: "/door-sliders/quilog-door-slider" },
      { url: "/door-sliders/freight-elevator-door-slider" },
      { url: "/door-sliders/m-door-slider" },
    ],
  },
  {
    slug: "guide-shoes",
    page_name: "Guide Shoes",
    canonical: "https://www.bestechparts.ae/products/guide-shoes",
    items: [
      { url: "/guide-shoes/guide-shoe-100-100-10-16-s" },
      { url: "/guide-shoes/guide-shoe-65-10-16-s" },
      { url: "/guide-shoes/guide-shoe-insert-145-36-o" },
      { url: "/guide-shoes/general-guide-shoe-insert-120-10-16" },
      { url: "/guide-shoes/guide-shoe-insert-230-10-16-m" },
      { url: "/guide-shoes/guide-shoe-wheel-100-25-62052" },
      { url: "/guide-shoes/guide-shoe-120-10-16" },
      { url: "/guide-shoes/guide-shoe-110-10-16" },
      { url: "/guide-shoes/guide-shoe-120-10-16-alt" },
      { url: "/guide-shoes/guide-shoe-80-10-16" },
      { url: "/guide-shoes/guide-shoe-km924-10g-g16a" },
      { url: "/guide-shoes/guide-shoe-l10" },
      { url: "/guide-shoes/guide-shoe-100-10-16" },
      { url: "/guide-shoes/general-guide-shoe-dx18" },
      { url: "/guide-shoes/general-guide-shoe-dx-10a" },
      { url: "/guide-shoes/guide-shoe-110-10-16-alt" },
      { url: "/guide-shoes/guide-shoe-150-10-16" },
      { url: "/guide-shoes/guide-shoe-insert-100-10-16" },
      { url: "/guide-shoes/guide-shoe-insert-80-10-16" },
      { url: "/guide-shoes/guide-shoe-insert-140-10-16" },
      { url: "/guide-shoes/guide-shoe-insert-20-10-16" },
      { url: "/guide-shoes/guide-shoe-insert-140-x-10-16" },
      { url: "/guide-shoes/guide-shoe-insert-230-10-16-alt" },
      { url: "/guide-shoes/guide-shoe-insert-100-10-16-alt" },
      { url: "/guide-shoes/guide-shoe-insert-125-10-16" },
      { url: "/guide-shoes/guide-shoe-wheel-76-21-6203" },
      { url: "/guide-shoes/guide-shoe-wheel-125-22-6303" },
      { url: "/guide-shoes/guide-shoe-wheel-150-32-6203" },
      { url: "/guide-shoes/guide-shoe-wheel-80-24-6203" },
      { url: "/guide-shoes/guide-shoe-sg12-sg13-t" },
      { url: "/guide-shoes/guide-shoe-140-10-15" },
      { url: "/guide-shoes/general-guide-shoe-insert-140-10-16" },
    ],
  },
  {
    slug: "sensors",
    page_name: "Sensors",
    canonical: "https://www.bestechparts.ae/products/sensors",

    items: [
      { url: "/sensors/load-sensor-dw-c1" },
      { url: "/sensors/leveling-sensor-61u-61n-30-77u-77n" },
      { url: "/sensors/u-type-leveling-sensor" },
      { url: "/sensors/leveling-sensor-gls126nt2ncno" },
      { url: "/sensors/leveling-sensor-yg-28-25-2561-128" },
      { url: "/sensors/leveling-sensor-zpad01-001" },
      { url: "/sensors/leveling-sensor-gls-tk" },
      { url: "/sensors/leveling-sensor-mkf71asakx" },
      { url: "/sensors/light-curtain-door-sensor-center-open" },
      { url: "/sensors/light-curtain-door-sensor-side-open" },
    ],
  },
  {
    slug: "door-wheels",
    page_name: "Door Wheels",
    canonical: "https://www.bestechparts.ae/products/door-wheels",
    items: [
      { url: "/door-wheels/door-hanging-wheel-small-85-20-6204" },
      { url: "/door-wheels/door-hanging-wheel-big-140-20-6204" },
      { url: "/door-wheels/door-hanging-wheel-52-16-6003" },
      { url: "/door-wheels/door-hanging-wheel-50-14-6201" },
      { url: "/door-wheels/door-hanging-wheel-94-19-6203" },
      { url: "/door-wheels/door-hanging-wheel-74-18-6203" },
      { url: "/door-wheels/door-hanging-wheel-c144aanp" },
      { url: "/door-wheels/door-belt-wheel-pwvc" },
      { url: "/door-wheels/door-belt-wheel-38-20-6000" },
      { url: "/door-wheels/door-belt-wheel-f9" },
      { url: "/door-wheels/door-machine-positioning-wheel" },
      { url: "/door-wheels/door-hanging-wheel-56-16-6201" },
      { url: "/door-wheels/door-wheel-56-14-6201" },
      { url: "/door-wheels/door-hanging-wheel-70-17-6200" },
      { url: "/door-wheels/door-hanging-wheel-48-14-6200" },
      { url: "/door-wheels/door-hanging-wheel-45-16-6000" },
      { url: "/door-wheels/door-hanging-wheel-16508792-16502278" },
      { url: "/door-wheels/door-hanging-wheel-65-13-6202" },
      { url: "/door-wheels/door-hanging-wheel-62-16-6203" },
      { url: "/door-wheels/door-wheel-bracket-amd" },
      { url: "/door-wheels/door-wheel-3201-05-0032-c" },
    ],
  },
  {
    slug: "door-locks",
    page_name: "Door Locks",
    canonical: "https://www.bestechparts.ae/products/door-locks",
    items: [
      { url: "/door-locks/door-triangle-lock" },
      { url: "/door-locks/door-lock-contact-az-05" },
      { url: "/door-locks/cop-lock-key-10001" },
      { url: "/door-locks/landing-door-lock-mkg-161-06" },
      { url: "/door-locks/door-lock-contact-az-06" },
      { url: "/door-locks/cop-lock-e-431" },
      { url: "/door-locks/landing-door-lock-g509-102121a" },
      { url: "/door-locks/door-lock-contact-az14-1kd" },
      { url: "/door-locks/door-lock-contact-ty-161" },
      { url: "/door-locks/triangle-lock" },
      { url: "/door-locks/door-lock-contact-kf-9074" },
      { url: "/door-locks/door-lock-contact-kf-zv" },
      { url: "/door-locks/lop-lock-all-fan-vip" },
      { url: "/door-locks/lop-lock-jjxe-d-01" },
      { url: "/door-locks/lop-lock-cv50-cv180" },
      { url: "/door-locks/door-lock-device-dk-rn4" },
      { url: "/door-locks/door-lock-contact-bh-253" },
      { url: "/door-locks/door-lock-contact-az-061" },
      { url: "/door-locks/door-lock-wheel-3201-05-0013-c" },
      { url: "/door-locks/door-triangle-lock-xq" },
      { url: "/door-locks/lop-lock-2801-2802-2803" },
      { url: "/door-locks/door-lock-contact-se11-1a12" },
      { url: "/door-locks/landing-door-lock-device-50-11-left" },
      { url: "/door-locks/landing-door-lock-device-50-11-right" },
      { url: "/door-locks/door-lock-contact-asme" },
      { url: "/door-locks/door-lock-contact-edc-92l-edc-61l" },
      { url: "/door-locks/door-closer" },
      { url: "/door-locks/cop-lock" },
      { url: "/door-locks/door-lock-contact-161" },
    ],
  },
  {
    slug: "mechanical",
    page_name: "Mechanical",
    items: [
      { url: "/mechanical/rivet-nuts-jx-f-m3-r-st" },
      { url: "/mechanical/rivet-nuts-jx-f-m4-r-st" },
      { url: "/mechanical/rivet-nuts-jx-f-m5-r-st" },
      { url: "/mechanical/rivet-nuts-jx-f-m6-r-st" },
      { url: "/mechanical/steel-socket-head-screws-m3x20mm" },
      { url: "/mechanical/steel-socket-head-screws-m3x30mm" },
      { url: "/mechanical/steel-socket-head-screws-m4x20mm" },
      { url: "/mechanical/steel-socket-head-screws-m4x30mm" },
      { url: "/mechanical/steel-socket-head-screws-m5x20mm" },
      { url: "/mechanical/steel-socket-head-screws-m5x30mm" },
      { url: "/mechanical/steel-socket-head-screws-m6x20mm" },
      { url: "/mechanical/steel-socket-head-screws-m6x30mm" },
      { url: "/mechanical/battery-rivet-machine" },
    ],
  },
  {
    slug: "cabinet-set",
    page_name: "Cabinet Set",
    canonical: "https://www.bestechparts.ae/products/cabinet-set",
    items: [
      { url: "/cabinet-set/control-cabinet-w8l-11kw" },
      { url: "/cabinet-set/control-cabinet-w8l-75kw" },
      { url: "/cabinet-set/car-top-communication-box" },
      { url: "/cabinet-set/socket-and-wire-20cm" },
      { url: "/cabinet-set/din-rail-35mm-2m" },
      { url: "/cabinet-set/trunking-2m" },
      { url: "/cabinet-set/braking-resistor-2500w" },
      { url: "/cabinet-set/braking-resistor-3500w" },
      { url: "/cabinet-set/braking-resistor-5500w" },
    ],
  },
  {
    slug: "electrical",
    page_name: "Electrical",
    canonical: "https://www.bestechparts.ae/products/electrical",
    items: [
      { url: "/electrical/connector-pt2-5" },
      { url: "/electrical/connector-pt6" },
      { url: "/electrical/connector-pt10" },
      { url: "/electrical/inspection-box" },
      { url: "/electrical/switching-power-supply-smps" },
      { url: "/electrical/phase-sequence-relay" },
      { url: "/electrical/intercom-handset" },
      { url: "/electrical/intercom-cop-unit" },
      { url: "/electrical/power-supply-unit" },
      { url: "/electrical/emergency-light" },
      { url: "/electrical/alarm" },
    ],
  },
  {
    slug: "switches",
    page_name: "Switches",
    canonical: "https://www.bestechparts.ae/products/switches",
    items: [
      { url: "/switches/inspection-normal-switch-no" },
      { url: "/switches/inspection-normal-switch-light-no" },
      { url: "/switches/bistable-switch-mkg131-03" },
      { url: "/switches/emergency-stop-switch-lay7" },
      { url: "/switches/buffer-switch-uks-ukt" },
      { url: "/switches/pit-buffer-switch-lxp1-3SE3-020-1a" },
      { url: "/switches/door-switch-ds-131" },
      { url: "/switches/door-machine-switch-ya043d166-04" },
      { url: "/switches/limit-switch-d4na-4132-d4n-4a72" },
      { url: "/switches/overload-switch-hd-mv01a" },
      { url: "/switches/micro-switch-x-10gq-b" },
      { url: "/switches/limit-switch-s3-b1270-s3-1371" },
      { url: "/switches/brake-detection-switch-b3181-83186" },
      { url: "/switches/door-switch-kcb-jua-kcb-jub" },
      { url: "/switches/bistable-switch" },
      { url: "/switches/monostable-switch" },
    ],
  },
  {
    slug: "buttons",
    page_name: "Buttons",
    canonical: "https://www.bestechparts.ae/products/buttons",
    items: [
      { url: "/buttons/stop-push-button-nc" },
      { url: "/buttons/white-arrow-button-no" },
      { url: "/buttons/black-arrow-button-no" },
      { url: "/buttons/green-push-button-with-light-no" },
      { url: "/buttons/red-push-button-with-light-no" },
      { url: "/buttons/button-kds330-kds220" },
      { url: "/buttons/button-mtd482-da482a101" },
      { url: "/buttons/button-mtd340" },
      { url: "/buttons/button-ak2026f" },
      { url: "/buttons/button-br27c-a311" },
      { url: "/buttons/button-cn03010009-a4j16354" },
      { url: "/buttons/button-a3n47136-kas441" },
      { url: "/buttons/button-a3n47325-aj47324a2" },
      { url: "/buttons/button-kd550" },
      { url: "/buttons/square-button-kds300" },
      { url: "/buttons/button-kmbs7782g0" },
      { url: "/buttons/giant-button-a4j16467-a4j16465-a4j20057" },
      { url: "/buttons/button-mtd511g01-da511g01" },
      { url: "/buttons/button-da180-mtd180" },
      { url: "/buttons/button-sl-tc" },
      { url: "/buttons/button-hd60-1" },
      { url: "/buttons/button-kas040-amv243-aad7442" },
      { url: "/buttons/button-cs-41-gg" },
      { url: "/buttons/button-mtd118" },
      { url: "/buttons/button-a4j13868-a4n13869" },
      { url: "/buttons/emergency-light-round-cop" },
      { url: "/buttons/button-da411-b113-mtd411" },
      { url: "/buttons/cop-button-open" },
      { url: "/buttons/cop-button-close" },
      { url: "/buttons/cop-button-p1" },
      { url: "/buttons/cop-button-p2" },
      { url: "/buttons/cop-button-p3" },
      { url: "/buttons/cop-button-p4" },
      { url: "/buttons/cop-button-p5" },
      { url: "/buttons/cop-button-g" },
      { url: "/buttons/cop-button-m" },
      { url: "/buttons/cop-button-1" },
      { url: "/buttons/cop-button-2" },
      { url: "/buttons/cop-button-3" },
      { url: "/buttons/cop-button-4" },
      { url: "/buttons/cop-button-5" },
      { url: "/buttons/cop-button-6" },
      { url: "/buttons/cop-button-7" },
      { url: "/buttons/cop-button-8" },
      { url: "/buttons/cop-button-9" },
      { url: "/buttons/cop-button-10" },
      { url: "/buttons/cop-button-11" },
      { url: "/buttons/cop-button-12" },
      { url: "/buttons/cop-button-r" },
      { url: "/buttons/cop-button-alarm" },
    ],
  },
  {
    slug: "circuit-breakers",
    page_name: "Circuit Breakers",
    canonical: "https://www.bestechparts.ae/products/circuit-breakers",
    items: [
      { url: "/circuit-breakers/mcb-63a-4p" },
      { url: "/circuit-breakers/mcb-6a-1p" },
      { url: "/circuit-breakers/mcb-10a-1p" },
      { url: "/circuit-breakers/mcb-6a-2p" },
      { url: "/circuit-breakers/mcb-10a-2p" },
    ],
  },
  {
    slug: "contactors",
    page_name: "Contactors",
    canonical: "https://www.bestechparts.ae/products/contactors",
    items: [
      { url: "/contactors/contactor-ac110v-25a-1no-1nc" },
      { url: "/contactors/contactor-ac110v-32a-1no-1nc" },
      { url: "/contactors/contactor-ac110v-50a-1no-1nc" },
      { url: "/contactors/contactor-ac110v-65a-1no-1nc" },
      { url: "/contactors/contactor-dc110v-18a" },
      { url: "/contactors/contactor-dc110v-32a" },
      { url: "/contactors/auxiliary-f4-22-2no-2nc" },
    ],
  },
  {
    slug: "cables-and-wires",
    page_name: "Cables and Wires",
    canonical: "https://www.bestechparts.ae/products/cables-and-wires",
    items: [
      { url: "/cables-and-wires/wire-0-75mm" },
      { url: "/cables-and-wires/wire-6mm" },
      { url: "/cables-and-wires/wire-8mm" },
      { url: "/cables-and-wires/wire-10mm" },
      { url: "/cables-and-wires/wire-lugs-0-75mm" },
      { url: "/cables-and-wires/wire-lugs-1-5mm" },
      { url: "/cables-and-wires/wire-lugs-6mm" },
      { url: "/cables-and-wires/wire-lugs-10mm" },
      { url: "/cables-and-wires/cable-db9-5m" },
      { url: "/cables-and-wires/cable-db9-10m" },
      { url: "/cables-and-wires/cable-command-board-70cm" },
      { url: "/cables-and-wires/display-mitsubishi-modbus-cable" },
    ],
  },
  {
    slug: "connectors",
    page_name: "Connectors",
    code: "BS-EU",
    items: [
      { url: "/connectors/connector-pt2-5-bs-eu0001" },
      { url: "/connectors/connector-pt6-bs-eu0002" },
      { url: "/connectors/connector-pt10-bs-eu0003" },
    ],
  },
];
